scopes:
  comments:
    - comment
    - punctuation.definition.comment # start and end of comment blocks
  functions:
    - entity
    - entity.name.function
    - punctuation.definition.entity # css . and # for classes and IDs
    - support.function
  keywords:
    - keyword
    - punctuation.definition.keyword # css @ in @media queries
  primitives:
    - constant
    - keyword.other
    - support.type
  punctuation:
    - meta.brace
    - punctuation
  storage:
    - storage
    - support.class
    - support.constant
  strings:
    - string
    - markup.inline
  tags:
    - entity.name
    - variable.language # this
  variables:
    - support.type.property-name
    - support.variable
    - variable

styles:
  bold:
    - markup.bold
    - punctuation.definition.bold
    - entity.other.attribute-name.id # css ID
  italic:
    - comment
    - markup.italic
    - punctuation.definition.italic

workbench:
  primary:
    - activityBarBadge.background
    - button.background
  secondary:
    - activityBar.activeBorder
    - editor.findMatchBorder
    - editor.wordHighlightBorder
    - editor.wordHighlightStrongBorder
    - editorBracketMatch.border
    - editorHoverWidget.border
    - editorInfo.foreground
    - editorOverviewRuler.infoForeground
    - editorSuggestWidget.border
    - focusBorder
    - inputOption.activeBorder
    - inputValidation.infoBackground
    - inputValidation.infoBorder
    - peekView.border
  warning:
    - editorOverviewRuler.warningForeground
    - editorWarning.foreground
    - inputValidation.warningBackground
    - inputValidation.warningBorder
    - list.warningForeground
  error:
    - editorError.foreground
    - editorOverviewRuler.errorForeground
    - errorForeground
    - inputValidation.errorBackground
    - inputValidation.errorBorder
    - list.errorForeground
  borders:
    - activityBar.border
    - contrastBorder
    - dropdown.border
    - editorGroup.border
    - editorOverviewRuler.border
    - input.background
    - inputValidation.infoForeground
    - inputValidation.warningForeground
    - panel.border
    - sideBar.border
    - statusBar.border
    - tab.border
    - titleBar.border
  background:
    - activityBar.background
    - editor.background
    - sideBarSectionHeader.background
    - statusBar.background
    - tab.activeBackground
    - titleBar.activeBackground
    - titleBar.inactiveBackground
  panels:
    - activityBar.activeBackground
    - activityBar.dropBackground
    - debugToolBar.background
    - dropdown.background
    - editorGroup.background
    - editorGroupHeader.tabsBackground
    - editorHoverWidget.background
    - editorSuggestWidget.background
    - editorWidget.background
    - notificationCenterHeader.background
    - notifications.background
    - panel.background
    - peekViewEditor.background
    - peekViewResult.background
    - peekViewTitle.background
    - sideBar.background
    - statusBar.debuggingBackground
    - statusBar.noFolderBackground
    - statusBarItem.hoverBackground
    - tab.inactiveBackground
  text_subtle:
    - activityBar.inactiveForeground
    - editorLineNumber.foreground
    - tab.inactiveForeground
    - titleBar.inactiveForeground
  text:
    - editor.foreground
    - editorCursor.foreground
    - statusBar.foreground
    - terminal.foreground
  text_active:
    - editorActiveLineNumber.foreground
    - list.inactiveSelectionForeground
    - peekViewResult.selectionForeground
    - tab.activeForeground
    - titleBar.activeForeground
  highlight:
    - editor.lineHighlightBackground
    - editor.selectionHighlightBackground
    - editorIndentGuide.background
    - editorRuler.foreground
    - editorSuggestWidget.selectedBackground
    - editorWhitespace.foreground
    - list.hoverBackground
    - peekViewResult.selectionBackground
    - scrollbarSlider.background
    - tab.hoverBackground
  highlight_active:
    - editor.selectionBackground
    - editorIndentGuide.activeBackground
    - list.activeSelectionBackground
    - list.focusBackground
    - list.inactiveSelectionBackground
    - peekViewEditor.matchHighlightBackground
    - peekViewResult.matchHighlightBackground
    - scrollbarSlider.activeBackground
    - scrollbarSlider.hoverBackground
  highlight_border:
    - editor.findMatchHighlightBorder
    - editor.rangeHighlightBorder
    - editor.selectionHighlightBorder
  transparent:
    - editor.findMatchBackground
    - editor.findMatchHighlightBackground
    - editor.lineHighlightBorder
    - editor.wordHighlightBackground
    - editor.wordHighlightStrongBackground
    - editorBracketMatch.background
    - scrollbar.shadow
    - widget.shadow
  white:
    - activityBar.foreground
    - activityBarBadge.foreground
  git_untracked:
    - gitDecoration.untrackedResourceForeground
  git_modified:
    - gitDecoration.modifiedResourceForeground
  git_deleted:
    - gitDecoration.deletedResourceForeground
