# Your theme's name must begin with Plastic, e.g. Plastic Horses
name: Plastic

palette:
  dodger_blue: '#1085FF'
  atlantis: '#69c52e'
  bright_turquoise: '#08E8DE'
  bunker: '#0D1117'
  cadet_blue: '#A9B2C3'
  cadet_blue_1A: '#A9B2C31A'
  cadet_blue_33: '#A9B2C333'
  cornflower_blue: '#61AFEF'
  electric_violet: '#8B00FF'
  fountain_blue: '#56B6C2'
  harvest_gold: '#E5C07B'
  iron: '#D4D7D9'
  lavender: '#B57EDC'
  olivine: '#98C379'
  rob_roy: '#E9D16C'
  shark: '#21252B'
  shuttle_gray: '#5F6672'
  sunglo: '#E06C75'
  whiskey: '#D19A66'
  woodsmoke: '#181A1F'
  transparent: '#00000000'
  valencia: '#D74E42'
  white: '#ffffff'

terminal:
  shark: terminal.ansiBlack
  cornflower_blue: terminal.ansiBlue
  fountain_blue: terminal.ansiCyan
  olivine: terminal.ansiGreen
  lavender: terminal.ansiMagenta
  sunglo: terminal.ansiRed
  whiskey: terminal.ansiYellow
  cadet_blue: terminal.ansiWhite
  shuttle_gray: terminal.ansiBrightBlack
  dodger_blue: terminal.ansiBrightBlue
  bright_turquoise: terminal.ansiBrightCyan
  atlantis: terminal.ansiBrightGreen
  electric_violet: terminal.ansiBrightMagenta
  valencia: terminal.ansiBrightRed
  rob_roy: terminal.ansiBrightYellow
  iron: terminal.ansiBrightWhite

default_syntax:
  # comments
  shuttle_gray:
    - comment
    - punctuation.definition.comment # start and end of comment blocks
  # functions
  lavender:
    - entity.name.function
    - support.function
  # import, export, return etc.
  sunglo:
    - keyword
    - punctuation.definition.keyword # css @ in @media queries
    - variable.language # this
  # primitives
  fountain_blue:
    - constant
    - support.constant
  # const, var, class etc. and React JSX component tag
  cornflower_blue:
    - storage
    - support.class # console and JSX custom components
  # anything in quotes
  olivine:
    - markup.inline.raw.string # inline code in markdown
    - string
  # html tags and types
  harvest_gold:
    - entity.name.section
    - entity.name.tag
    - entity.name.type
    - support.type
  # variables
  iron:
    - support.type.property-name # css property names
    - support.variable
    - variable
  whiskey:
    - entity.other
    - punctuation.definition.entity # css . and # for CSS classes and IDs
    - support.other

normal_syntax:
  # quotes, terminators etc.
  cadet_blue:
    - meta.brace
    - punctuation

deprioritised_syntax:
  # quotes, terminators etc.
  shuttle_gray:
    - meta.brace
    - punctuation

styles:
  bold:
    - markup.bold
    - punctuation.definition.bold
    - entity.other.attribute-name.id # css ID
  italic:
    - comment
    - markup.italic
    - punctuation.definition.italic

workbench:
  # green
  olivine:
    - gitDecoration.untrackedResourceForeground
  # amber
  whiskey:
    - gitDecoration.modifiedResourceForeground
  # red. buttons, activity-bar badge
  sunglo:
    - activityBarBadge.background
    - button.background
    - gitDecoration.deletedResourceForeground
  # find highlight, bracket match etc.
  dodger_blue:
    - activityBar.activeBorder
    - editor.findMatchBorder
    - editor.wordHighlightBorder
    - editor.wordHighlightStrongBorder
    - editorBracketMatch.border
    - editorHoverWidget.border
    - editorInfo.foreground
    - editorLightBulbAutoFix.foreground
    - editorOverviewRuler.infoForeground
    - editorSuggestWidget.border
    - focusBorder
    - inputOption.activeBorder
    - inputValidation.infoBackground
    - inputValidation.infoBorder
    - peekView.border
    - tab.activeBorderTop
  # warning. squiggly underlines, find match errors etc.
  rob_roy:
    - editorLightBulb.foreground
    - editorOverviewRuler.warningForeground
    - editorWarning.foreground
    - inputValidation.warningBackground
    - inputValidation.warningBorder
    - list.warningForeground
  # error. squiggly underlines, find match errors etc.
  valencia:
    - editorError.foreground
    - editorOverviewRuler.errorForeground
    - errorForeground
    - inputValidation.errorBackground
    - inputValidation.errorBorder
    - list.errorForeground
  # borders that separate the panels, sidebars, tabs etc.
  bunker:
    - activityBar.border
    - contrastBorder
    - dropdown.border
    - editorGroup.border
    - editorOverviewRuler.border
    - input.background
    - inputValidation.infoForeground
    - inputValidation.warningForeground
    - notificationCenter.border
    - notificationToast.border
    - notifications.border
    - panel.border
    - sideBar.border
    - statusBar.border
    - tab.border
    - titleBar.border
  # editor, titlebar, and activity bar background
  shark:
    - activityBar.background
    - editor.background
    - sideBarSectionHeader.background
    - statusBar.background
    - tab.activeBackground
    - titleBar.activeBackground
    - titleBar.inactiveBackground
  # sidebar, terminal, inactive tabs etc.
  woodsmoke:
    - activityBar.dropBackground
    - debugToolBar.background
    - dropdown.background
    - editorGroup.background
    - editorGroupHeader.tabsBackground
    - editorHoverWidget.background
    - editorSuggestWidget.background
    - editorWidget.background
    - notificationCenterHeader.background
    - notifications.background
    - panel.background
    - peekViewEditor.background
    - peekViewResult.background
    - peekViewTitle.background
    - sideBar.background
    - statusBar.debuggingBackground
    - statusBar.noFolderBackground
    - statusBarItem.hoverBackground
    - tab.inactiveBackground
  # line numbers, muted items
  shuttle_gray:
    - activityBar.inactiveForeground
    - editorLineNumber.foreground
    - tab.inactiveForeground
    - titleBar.inactiveForeground
  # text
  cadet_blue:
    - editor.foreground
    - editorCursor.foreground
    - statusBar.foreground
    - terminal.foreground
  # active tab, active line number, active list text etc. Search match borders
  iron:
    - editor.findMatchHighlightBorder
    - editor.rangeHighlightBorder
    - editor.selectionHighlightBorder
    - editorActiveLineNumber.foreground
    - list.inactiveSelectionForeground
    - peekViewResult.selectionForeground
    - tab.activeForeground
    - titleBar.activeForeground
  # ui flourishes: whitespace, indent guide, ruler, line highlight
  cadet_blue_1A:
    - editor.lineHighlightBackground
    - editor.selectionHighlightBackground
    - editorIndentGuide.background
    - editorRuler.foreground
    - editorSuggestWidget.selectedBackground
    - editorWhitespace.foreground
    - list.hoverBackground
    - peekViewResult.selectionBackground
    - scrollbarSlider.background
    - tab.hoverBackground
  # active indent guide, selection, search match
  cadet_blue_33:
    - editor.selectionBackground
    - editorIndentGuide.activeBackground
    - list.activeSelectionBackground
    - list.focusBackground
    - list.inactiveSelectionBackground
    - peekViewEditor.matchHighlightBackground
    - peekViewResult.matchHighlightBackground
    - scrollbarSlider.activeBackground
    - scrollbarSlider.hoverBackground
  # a few tweaks to some backgrounds and highlights
  transparent:
    - editor.findMatchBackground
    - editor.findMatchHighlightBackground
    - editor.lineHighlightBorder
    - editor.wordHighlightBackground
    - editor.wordHighlightStrongBackground
    - editorBracketMatch.background
    - scrollbar.shadow
    - widget.shadow
  # some active items and text, that just looks better as pure white
  white:
    - activityBar.foreground
    - activityBarBadge.foreground
